DELETE http://localhost:3001/api/persons/58
###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "s", 
    "number": "19-43-234347"
}

###
PUT http://localhost:3001/api/persons/64dcac8d6698f3a31867e29c 
content-type: application/json

{
    "name": "he",
    "number": "040-1111111"
}