###
GET http://localhost:3003/api/blogs/ 

###
POSt http://localhost:3003/api/blogs/ 
content-type: application/json

{
      "title": "hem sir ko danger love story",
  "author": "sunil xunu munu",
  "url": "http://www.myblog.com",
  "likes": 1000
}