###
GET http://localhost:3003/api/blogs/ 

###
POSt http://localhost:3001/api/blogs/ 
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrYXNoIiwiaWQiOiI2NTI0MTNiNDBiMDg2YjhjNzFkNDc2NzEiLCJpYXQiOjE2OTc2MzA0NDIsImV4cCI6MTY5NzYzMzE0Mn0.1XdpDwdU9HksH0zJHxU16G21sueaCSi6lUrtt5XRmiM

{
  "title":"new blog 4",
  "author": "himal",
  "url": "http://www.myblog.com",
  "likes":400,
  "userId":"652413b40b086b8c71d47671"
 }

###
DELETE http://localhost:3001/api/blogs/652c2d9b6e8b24b9dd304e36
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrYXNoIiwiaWQiOiI2NTI0MTNiNDBiMDg2YjhjNzFkNDc2NzEiLCJpYXQiOjE2OTc2MzA0NDIsImV4cCI6MTY5NzYzMzE0Mn0.1XdpDwdU9HksH0zJHxU16G21sueaCSi6lUrtt5XRmiM



###
PUT http://localhost:3003/api/blogs/64e8de076df910abc64cd8a2
Content-Type: application/json

{
  "likes":5000
}

###
POSt http://localhost:3001/api/users/ 
content-type: application/json

{
  "username":"himal",
  "name":"Himal Sunar",
  "password":"55555"
 }

###
POSt http://localhost:3001/api/login/ 
content-type: application/json

{
  "username":"akash",
  "password":"44444"
 }