POST http://localhost:3001/api/blogs
content-type: application/json

{
   "author": "Akash sunar",
    "title": "The untold story",
    "url": "http://www.akash.com",
    "likes": 9
}

###
GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/4

###
PUT http://localhost:3001/api/blogs/8

